<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> meeting deletion' => '<strong>Löschvorgang</strong> bestätigen',
    '<strong>Create</strong> new meeting' => '<strong>Neue</strong> Besprechung erstellen',
    '<strong>Edit</strong> meeting' => '<strong>Besprechung</strong> bearbeiten',
    'Add external participants (free text)' => 'Externe Teilnehmer hinzufügen (Freitext)',
    'Add participants' => 'Teilnehmer hinzufügen',
    'Do you really want to delete this meeting?' => 'Möchtest du diese Besprechung wirklich löschen?',
    'External participants' => 'Externe Teilnehmer',
    'Location' => 'Ort',
    'Room' => 'Raum',
    'Title of your meeting' => 'Titel der Besprechung',
    'hh:mm' => 'hh:mm',
];
