<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Share</strong> meeting' => '<strong>Besprechung</strong> teilen',
    'Add to your calendar and invite participants' => 'Zum Kalender hinzufügen und Teilnehmer einladen',
    'Add to your personal calendar' => 'Zum persönlichen Kalender hinzufügen',
    'Export ICS' => 'Exportiere ICS',
    'Send notifications to all participants' => 'Benachrichtigungen an alle Teilnehmer senden',
    'Send now' => 'Jetzt senden',
    'Sends internal notifications to all participants of the meeting.' => 'Sendet interne Benachrichtigungen an alle Teilnehmer.',
    'This will create an ICS file, which adds this meeting only to your private calendar.' => 'Erstellt eine ICS-Datei, welche diese Besprechung ausschließlich zu deinem persönlichen Kalender hinzufügt.',
    'This will create an ICS file, which adds this meeting to your personal calendar, invite all other participants by email and waits for their response.' => 'Erstellt eine ICS-Datei, welche diese Besprechung zu deinem persönlichen Kalender hinzufügt, alle anderen Teilnehmer automatisch per Email einladet und dessen Zusagen/Absagen einfordert.',
];
