<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> entry deletion' => '<strong>Löschvorgang</strong> bestätigen',
    '<strong>Create</strong> new entry' => '<strong>Neuen</strong> Tagesordnungspunkt erstellen',
    '<strong>Edit</strong> entry' => '<strong>Tagesordnungspunkt</strong> bearbeiten',
    'Add external moderators (free text)' => 'Externe Moderatoren hinzufügen (Freitext)',
    'Add moderator' => 'Moderator hinzufügen',
    'Do you really want to delete this entry?' => 'Möchtest du den Tagesordnungspunkt wirklich löschen?',
    'External moderators' => 'Externe Moderatoren',
    'Subject' => 'Beschreibung',
    'Title of this entry' => 'Titel des Tagesordnungspunktes',
];
